 - name: Create XFS filesystem
   filesystem:
     fstype: xfs
     dev: /dev/disk/azure/scsi1/lun0

 - name: Set proper permissions on mount point
   file:
     path: /var/lib/origin/openshift.local.volumes
     state: directory
     mode: 0755

 - name: Restore SELinux context
   command: restorecon -R /var/lib/origin/openshift.local.volumes
   changed_when: False

 - name: Get filesystem UUID
   command: blkid -sUUID -ovalue /dev/disk/azure/scsi1/lun0
   register: blkid

 - name: Mount XFS filesystem
   mount:
     state: mounted
     path: /var/lib/origin/openshift.local.volumes
     src: UUID={{ blkid.stdout }}
     fstype: xfs
     opts: gquota
