- name: Create XFS filesystem
  filesystem:
    fstype: xfs
    dev: /dev/disk/azure/scsi1/lun2

- name: Set proper permissions on mount point
  file:
    path: /var/lib/etcd
    state: directory
    mode: 0755

- name: Restore SELinux context
  command: restorecon -R /var/lib/etcd

- name: Get filesystem UUID
  command: blkid -sUUID -ovalue /dev/disk/azure/scsi1/lun2
  register: blkid

- name: Mount XFS filesystem
  mount:
    state: mounted
    path: /var/lib/etcd
    src: UUID={{ blkid.stdout }}
    fstype: xfs
